-- Cloud Resource Metadata and Usage Patterns
--  Write SQL queries to analyze cloud resource metadata and usage patterns stored in a relational database. 
-- The goal is to identify potential security risks such as over-privileged IAM roles, unused but exposed cloud resources, or anomalous resource usage patterns that might indicate compromise.